var Strings =
{
    'REMAINING_BOTTLES_FORMAT': '{0} bouteilles laissées',

    'SELECT_SITE_MSG':          'Choisir la site de Web.',
    'UPLOAD_SUCCESS_MSG':       'Fini de télécharger le fichier.',
    'TAX_INCLUDED_MSG':         'Le prix de la liste inclut la taxe.',
    'EMPTY_FLD_MSG':            'Veuillez compléter ce champ.',
    'INVALID_NUMBER_MSG':       'Veuillez mettre un numéro valide.',
    'OLD_IE_MSG':               'Vous utilisez ancienne version d\'Internet Explorer. Veuillez cliquer sur l\'un des liens ci-dessous et mettre à jour votre Internet Explorer.',
    'UNDER_CONSTRUCTION_MSG':   'Le contenu est en cours de construction. Désolé pour le désagrément.',
    'SUBSCRIBE_TO_ANYWAY_MAIL_MAGAZINE_MSG': 'S\'abonner au magazine e-mail de "Conceptual Wine Boutique Anyway-Grapes".',
    'INVALID_BARCODE_FOR_WINE_MSG': 'L\'article avec le code à barres spécifié n\'est pas un vin. S\'il vous plaît retaper un code à barres.',
    'ADDED_TO_CART_MSG':      '{0} bouteilles ont été ajoutés au panier.',
    'ADDED_TO_HAPPY_BOX_MSG': '{0} bouteilles ont été ajoutés au Happy Box.',
    'NO_SALE_FOR_MINORS_MSG': 'Nous ne vendons pas d\'alcool aux mineurs .',

    'PREVIOUS_STR':  'précédent',
    'NEXT_STR':      'Suivant',
    'SUBSCRIBE_STR': 'S\'abonner',

    'FIND_BY_WINE_TYPE':     '> Trouver par le type de vin.',
    'FIND_BY_PRODUCER_NAME': '> Trouver par le nom du producteur.',
    'FIND_BY_VINTAGE':       '> Trouver par le millésime.',
    'FIND_BY_PRICE':         '> Trouver par le prix.',
    'FIND_BY_IMPORTER':      '> Trouver par l\'importateur.',

    'AGREE_STR':             'Accepter',
    'NOT_AGREE_STR':         'Ne pas d\'accord',
    'HONEY_SUBMENU':         'Miel',
    'OLIVE_OIL_SUBMENU':     'huile d\'olive',
    'MASTARD_SUBMENU':       'Mastard',
    'SALT_SUBMENU':          'Sel',
    'DRY_FRUIT_SUBMENU':     'Fruit sec',

    'CORPORATE_PROFILE_STR':      'Profil de la société',
    'PRIVACY_STR':                'Intimité',
    'COMMERCIAL_TRANSACTION_STR': 'Droit commercial spécifique',
    'PAYMENT_METHOD_STR':         'Mode de paiement',

    'SHOW_WINES_STR':        'Afficher les vins',
    'UPDATE_IE_STR':         'Mise à jour IE',
    'MITSUGETSU_STR':        'Mitsu-Getsu',
    'OFURO_STR':             'Ofuro',
    'ANYWAY_STR':            'Anyway',
    'ADMIN_PAGE_STR':        'Page pour gérer',
    'PRINT_WINELIST_STR':    'Imprimer la carte des vins',
    'MANAGE_DB_STR':         'Gérer base de donée',
    'MANAGE_ORDER_STR':      'Gérer les commandes',
    'MODIFY_DAILY_MENU_STR': 'Modifier menu du jour',
    'UPLOAD_IMG_STR':        'Télécharger l\'image',
    'DB_MANAGER_PAGE_STR':   'Gestionnaire de la Base',
    'SAKE_STR':              'Sake',
    'SHOCHU_STR':            'Shochu',
    'BRANDY_STR':            'Eau de Vie',
    'OTHER_DRINKS_STR':      Constants['fr']['OTHER_DRINKS_STR'],
    'WINE_LIST_STR':         Constants['fr']['WINE_LIST_STR'],

    'KATAKANA_STR':           Constants['fr']['KATAKANA_STR'],
    'ALPHABET_STR':           Constants['fr']['ALPHABET_STR'],

    'SIGN_IN_STR':             'Se connecter',
    'SIGN_OUT_STR':            'Déconnexion',
    'ESTIMATED_SHIPPING_DATE': 'Date estimée d\'expédition:&nbsp;<strong>{2}/{1}/{0}</strong>',
    'NINETEEN_THIRTIES_STR':  '1930',
    'NINETEEN_FORTIES_STR':   '1940',
    'NINETEEN_FIFTIES_STR':   '1950',
    'NINETEEN_SIXTIES_STR':   '1960',
    'NINETEEN_SEVENTIES_STR': '1970',
    'NINETEEN_EIGHTIES_STR':  '1980',
    'NINETEEN_NITIES_STR':    '1990',
    'DOUBLE_O_STR':           '2000',

    'THOUSAND_YEN_RANGE_STR':       'Gamme 1000 yen',
    'TWO_THOUSAND_YEN_RANGE_STR':   'Gamme 2000 yen',
    'THREE_THOUSAND_YEN_RANGE_STR': 'Gamme 3000 yen',
    'FOUR_THOUSAND_YEN_RANGE_STR':  'Gamme 4000 yen',
    'FIVE_THOUSAND_YEN_RANGE_STR':  'Gamme 5000 yen',
    'MORE_THAN_TEN_THOUSAND_STR':   'Plus de 10000 yens',

    'NEW_WINE_STR':          'Vin nouveau',
    'RECOMMENDED_WINE_STR':  'Vin Conseillé',
    'VINTAGE_INFO_STR':      'Info Millésimes',
    'MONTHLY_WINE_STR':      'Vin Mensuelle',
    'WINE_SEARCH_STR':       'Recherche avancée',
    'FAQ_STR':               'Questions fréquentes',
    'FAQ_STR':               'Questions fréquentes',
    'WINE_SET_STR':          'Set à vin',
    'PRODUCER_INFO_STR':     'Producteur Infos',
    'RANKING_STR':           'Classement',
    'RECOMMENDED_LABEL_STR': 'Êtiquette Recommandé',
    'SALE_STR':         'Soldes',
    'NEW_ARRIVAL':      'Nouvelle arrivee',
    'WINE_DETAIL_STR':  'Détail de vin',
    'IMPORTER_STR':     'Importateur',
    'CONTACT_STR':      'Contactez-nous',
    'CART_STR':         'Panier',
    'COMMERCIAL_TRANSACTION_STR': 'Loi sur les transactions commerciales spécifiées',
    'COMPANY_INFO_STR': 'Information de l\'entreprise',
    'DISH_STR':         'Le Plat',
    'DRINK_STR':        'Boisson',

    'GUARANTEED_QUALITY_STR': 'Garantie de qualité',
    'SHIPPING_FEE_STR':       'Frais d\'expédition',
    'BUSINESS_SALE_STR':      'Entreprise de vente',
    'USER_GUIDE_STR':         'Guide de l\'utilisateur',
    'HAPPY_BOX_GUIDE_STR':    'Comment commander Happy Box',
    'WHATS_NEW_STR':    'Quoi de neuf',
    'WINE_STR':         'Le Vin',
    'OLD_WINE_STR':     'Le Vieux Vin',
    'FOOD_STR':         'Aliment',
    'GROCERY_TYPE_STR': 'L\'épicerie',
    'WINE_GOODS_STR':   'Accessoire de vin',
    'REGISTER_STR':     'S\'inscrire',
    'OTHER_INFO_STR':    'Autres infos',
    'GLASS_WINE_STR':    Constants['fr']['GLASS_WINE_STR'],
    'BOTTLE_WINE_STR':   Constants['fr']['BOTTLE_WINE_STR'],
    'EVENT_STR':        'Evéntement',
    'PHOTO_STR':        'Photo',
    'MAP_STR':          'Plan du Site',
    'HOME_STR':         'Accueil',
    'SITE_TOP_STR':     'Haut du Site',
    'LANGUAGE_STR':     'Langue',
    'SEARCH_STR':       'Recherche',
    'SORT_ORDER_STR':   'Ordre de tri',
    'NUMBER_OF_MACHED_WINES': 'Nombre de vins assortis',
    'VIEW_DETAIL_STR':   'Voir les détails',

    'WINE_GLASS_STR':        'Verre de vin',
    'WINE_BASKET_STR':       'Panier',
    'CHAMPAGNE_STOPPER_STR': 'Bouchon de champagne',
    'LABEL_COLLECTOR_STR':   'Étiquette Collector',

    'TYPE_STR':            'Type',
    'WINE_TYPE_STR':       'Type de vin',
    'DISH_TYPE_STR':       'Type de plat',
    'GROCERY_TYPE_STR':    'Type de l\'épicerie',
    'WINE_GOODS_TYPE_STR': 'Type d\'accessoire de vin',
    'BRANDY_TYPE_STR':     'Type d\'eau de vie',
    'SAKE_TYPE_STR':       'Type de sake',
    'SHOCHU_TYPE_STR':     'Type de shochu',
    'DRINK_TYPE_STR':      'Type de boisson',
    'EVENT_YEAR_STR':      'Année de l\'événement',
    'PHOTO_TYPE_STR':      'Type de photo',

    'COLD_APPETIZER_STR': 'Hors d\'Oeuvres Froid',
    'HOT_APPETIZER_STR':  'Hors d\'Oeuvres Chaud',
    'FISH_DISH_STR':      'Poisson',
    'MEAT_DISH_STR':      'Viande',
    'GIBIER_STR':         'Gibier',
    'DRY_FRUIT_STR':      'Fruit sec',
    'MITSU_COURSE_STR':   'Menu de MITSU',
    'GETSU_COURSE_STR':   'Menu de GETSU',

    'AWAMORI_STR':        Constants['fr']['AWAMORI_STR'],
    'KOKUTOU_JOUCHU_STR': Constants['fr']['KOKUTOU_JOUCHU_STR'],
    'KOME_JOUCHU_STR':    Constants['fr']['KOME_JOUCHU_STR'],
    'MUGI_JOUCHU_STR':    Constants['fr']['MUGI_JOUCHU_STR'],
    'IMO_JOUCHU_STR':     Constants['fr']['IMO_JOUCHU_STR'],
    'KURI_JOUCHU_STR':    Constants['fr']['KURI_JOUCHU_STR'],

    'MITSUGETSU_STAFF_STR':    'Equipe de Mitsu-Getsu',
    'MITSUGETSU_EVENT_STR':    'Evénement de Mitsu-Getsu',
    'OFURO_STAFF_STR':         'Equipe de Ofuro',
    'OFURO_EVENT_STR':         'Evénement de Ofuro',

    'SHOP_PHOTO_STR':          'Photos de la boutique',
    'TASTING_EVENT_PHOTO_STR': 'Dégustation',
    'DISH_PHOTO_STR':          'Photos de la cuisine',
    'MAGAZINE_PHOTO_STR':      'Photo du magazine',

    'SHOCHU_STR': Constants['fr']['SHOCHU_STR'],
    'SAKE_STR':   Constants['fr']['SAKE_STR'],

    'DAILY_MENU_STR':        Constants['fr']['DAILY_MENU_STR'],
    'NORMAL_MENU_STR':       Constants['fr']['NORMAL_MENU_STR'],
    'A_LA_CARTE':            Constants['fr']['A_LA_CARTE'],
    'COURSE_STR':            Constants['fr']['COURSE_STR'],
    'SMALL_DISH_STR':        'Le Petit Plat',
    'MAIN_DISH_STR':         'Le Plat Principal',
    'APPETIZER_STR':         'Entrée',
    'PASTA_STR':             'Pâtes',
    'GOHAN_STR':             'Gohan',
    'CHEESE_STR':            'Fromage',
    'DESSERT_STR':           'Dessert',
    'TEA_STR':               'Thé',
    'SPARKLING_WINE_STR':    Constants['fr']['SPARKLING_WINE_STR'],
    'CHAMPAGNE_STR':         'Champagne',
    'ROSE_WINE_STR':         Constants['fr']['ROSE_WINE_STR'],
    'WHITE_WINE_STR':        'Vin Blanc',
    'RED_WINE_STR':          'Vin Rouge',
    'ENGLISH_STR':           'Anglais',
    'FRENCH_STR':            'Français',
    'JAPANESE_STR':          'Japonais',

    'NEW_ITEM_STR':        'Nouveau Item',
    'INSERT_BELOW_STR':    'Insérer ci-dessous',
    'EDIT_STR':            'Modifier',
    'DELETE_STR':          'Supprimer',
    'EXPORT_TO_PNG':       'Exporter vers PNG',
    'SAVE_STR':            'Enregistrer',
    'CANCEL_STR':          'Annuler',
    'VINTAGE_STR':         'Millésime',
    'CAPACITY_STR':        'Capacité',
    'MONO_YEAR_STR':       'Mono Année',
    'PRODUCER_STR':        'Producteur',
    'LOC_PRODUCER_STR':    'Producteur(Japonais)',
    'FIRST_NAME_STR':      'First Name',
    'LAST_NAME_STR':       'Nom',
    'NAME_STR':            'Prénom',
    'LOC_NAME_STR':        'Nom(Japonais)',
    'ITEM_NAME_STR':       'Nom de l\'article',
    'BARCODE_STR':         'code à barres',
    'PRICE_STR':           'Prix',
    'MEMBER_PRICE_STR':    'Prix pour les membres',
    'GLASS_PRICE_STR':     'Prix (108ml)',
    'TOKKURI_PRICE_STR':   'Prix (180ml)',
    'INGREDIENT_STR':      'ingrédient',
    'BOTTLING_METHOD_STR': 'procédé d\'embouteillage',
    'ROMAJI_NAME_STR':     'Nom(Anglais)',
    'HIRAGANA_NAME_STR':   'Nom(Hiragana)',

    'EVENT_DATE_STR':    'Date de l\'événement',
    'EVENT_DESCRIPTION': 'Description de l\'événement',

    'ALCOHOL_STR':            'Degré Alcoolique',
    'VOLUME_STR':             'Volume',
    'COMMENT_STR':            'Commentaire',
    'ROSE_STR':               'Rosé',
    'COUNTRY_STR':            'pays',
    'AOC_STR':                'AOC',
    'LOC_AOC_STR':            'AOC(Japonais)',
    'REGION_STR':             'Région',
    'CEPAGE_STR':             'Cépage',
    'MONO_CEPAGE_STR':        'Mono-cépage',
    'CULTIVATION_METHOD_STR': 'Type de culture',
    'WINE_SCORE_STR':         'Le score du vin',
    'ADDRESS_STR':            'Adresse',
    'DELIVER_TO_STR':         'Livrer à',
    'TEL_STR':                'Numéro de Téléphone',
    'EMAIL_STR':              'Email',
    'OPENING_HOURS_STR':      'Heures d\'ouverture',
    'CLOSED_ON_STR':          'Fermé le',
    'URL_STR':                'Url',
    'MONTHLY_STR':            'Mensuellement',
    'QUANTITY_STR':           'Quantité',

    'NOT_SPECIFY_STR':   'Ne spécifiez pas.',
    'FILENAME_STR':      'Nom de Fichier',
    'TASTING_INFO_STR':  'Dégustation Infos',

        'SUNDAY_STR': 'dim',
        'MONDAY_STR': 'lun',
        'TUESDAY_STR': 'mar',
        'WEDNESDAY_STR': 'mer',
        'THURSDAY_STR': 'jeu',
        'FRIDAY_STR': 'ven',
        'SATURDAY_STR': 'sam',

    'FRANCE_STR':       Constants['fr']['FRANCE_STR'],
    'AUSTRALIA_STR':    Constants['fr']['AUSTRALIA_STR'],
    'GERMANY_STR':      Constants['fr']['GERMANY_STR'],
    'NEW_ZEALAND_STR':  Constants['fr']['NEW_ZEALAND_STR'],
    'ITALY_STR':        Constants['fr']['ITALY_STR'],
    'AMERICA_STR':      Constants['fr']['AMERICA_STR'],
    'SPAIN_STR':        Constants['fr']['SPAIN_STR'],
    'JAPAN_STR':        Constants['fr']['JAPAN_STR'],
    'AUSTRIA_STR':      Constants['fr']['AUSTRIA_STR'],
    'SOUTH_AFRICA_STR': Constants['fr']['SOUTH_AFRICA_STR'],
    'ENGLAND_STR':      Constants['fr']['ENGLAND_STR'],
    'CROATIA_STR':      Constants['fr']['CROATIA_STR'],
    'PORTUGAL_STR':     Constants['fr']['PORTUGAL_STR'],
    'CANADA_STR':       Constants['fr']['CANADA_STR'],
    'UKRAINE_STR':      Constants['fr']['UKRAINE_STR'],
    'ARGENTINA_STR':    Constants['fr']['ARGENTINA_STR'],
    'SWITZERLAND_STR':  Constants['fr']['SWITZERLAND_STR'],
    'BULGARIA_STR':     Constants['fr']['BULGARIA_STR'],
    'HANGARY_STR':      Constants['fr']['HANGARY_STR'],
    'LEBANON_STR':      Constants['fr']['LEBANON_STR'],
    'CHILE_STR':        Constants['fr']['CHILE_STR'],

        'RETAIL_PRICE_STR': 'Prix de détail',
        'MEMBER_PRICE_STR': 'Prix membre',
        'TAX_EXCLUDED_STR': 'HT',

        'CIRCLE_CHAR': '★',
        'WORD_SEPARATOR': ' ・ ',


        'YEAR_SYMBOL': '',
        'MONTH_SYMBOL': '',
        'DATE_SYMBOL': '',

        'SPARKLING_WINE_STR': Constants['fr']['SPARKLING_WINE_STR'],
        'WHITE_WINE_STR':     Constants['fr']['WHITE_WINE_STR'],
        'RED_WINE_STR':       Constants['fr']['RED_WINE_STR'],
        'ROSE_WINE_STR':      Constants['fr']['ROSE_WINE_STR'],

        'CHAMPAGNE_STR':       Constants['fr']['CHAMPAGNE_STR'],
        'CHAMPAGNE_ROSE_STR':  Constants['fr']['CHAMPAGNE_ROSE_STR'],
        'CREMANT_STR':         Constants['fr']['CREMANT_STR'],
        'PETILLANT_STR':       Constants['fr']['PETILLANT_STR'],
        'OTHER_SPARKLING_STR': Constants['fr']['OTHER_SPARKLING_STR'],
        'LORRAINE_STR':        Constants['fr']['LORRAINE_STR'],
        'ALSACE_STR':          Constants['fr']['ALSACE_STR'],
        'LOIRE_STR':           Constants['fr']['LOIRE_STR'],
        'BORDEAUX_STR':        Constants['fr']['BORDEAUX_STR'],
        'SUDWEST_STR':         Constants['fr']['SUDWEST_STR'],
        'BOURGOGNE_STR':       Constants['fr']['BOURGOGNE_STR'],
        'JURA_STR':            Constants['fr']['JURA_STR'],
        'SAVOIE_FRANCHE_STR':  Constants['fr']['SAVOIE_FRANCHE_STR'],
        'RHONE_STR':           Constants['fr']['RHONE_STR'],
        'LANG_ROUS_STR':       Constants['fr']['LANG_ROUS_STR'],
        'PROVENCE_STR':        Constants['fr']['PROVENCE_STR'],
        'CORSE_STR':           Constants['fr']['CORSE_STR'],
        'JURA_FRANCHE_STR':    Constants['fr']['JURA_FRANCHE_STR'],
        'LANGUEDOC_STR':       Constants['fr']['LANGUEDOC_STR'],
        'ROUSSILLON_STR':      Constants['fr']['ROUSSILLON_STR'],
        'OTHER_LANG_ROUS_STR': Constants['fr']['OTHER_LANG_ROUS_STR'],
        'FRANCE_MAIN_STR':     Constants['fr']['FRANCE_MAIN_STR'],

        'SPARKLING_ROSE_STR':   'Vin Mousseux Rosé',
        'FRENCH_WHITE_STR':     'Vin Blancs de France',
        'GERMAN_WHITE_STR':     'Vin Blancs d\'Allemagne',
        'AUSTRIAN_WHITE_STR':   'Vin Blancs d\'Autriche',
        'ITALIAN_WHITE_STR':    'Vin Blancs d\'Italie',
        'SPANISH_WHITE_STR':    'Vin Blancs d\'Espagne',
        'AMERICAN_WHITE_STR':   'Vin Blancs d\'Etats-Unis',
        'AUSTRALIAN_WHITE_STR': 'Vin Blancs d\'Australie',
        'NEWZEALAND_WHITE_STR': 'Vin Blancs de Nouvelle-Zélande',
        'FRENCH_RED_STR':       'Vin Rouges de France',
        'AUSTRIAN_RED_STR':     'Vin Rouges d\'Autriche',
        'GERMAN_RED_STR':       'Vin Rouges d\'Allemagne',
        'ITALIAN_RED_STR':      'Vin Rouges d\'Italie',
        'SPANISH_RED_STR':      'Vin Rouges d\'Espagne',
        'AMERICAN_RED_STR':     'Vin Rouges d\'Etats-Unis',
        'AUSTRALIAN_RED_STR':   'Vin Rouges d\'Australie',
        'NEWZEALAND_RED_STR':   'Vin Rouges de Nouvelle-Zélande',

        'HOKKAIDO_STR':  'Hokkaido',
        'AOMORI_STR':    'Aomori',
        'IWATE_STR':     'Iwate',
        'MIYAGI_STR':    'Miyagi',
        'AKITA_STR':     'Akita',
        'YAMAGATA_STR':  'Yamagata',
        'FUKUSHIMA_STR': 'Fukushima',
        'IBARAKI_STR':   'Ibaraki',
        'TOCHIGI_STR':   'Tochigi',
        'GUNMA_STR':     'Gunma',
        'SAITAMA_STR':   'Saitama',
        'CHIBA_STR':     'Chiba',
        'TOKYO_STR':     'Tokyo',
        'KANAGAWA_STR':  'Kanagawa',
        'NIIGATA_STR':   'Niigata',
        'TOYAMA_STR':    'Toyama',
        'ISHIKAWA_STR':  'Ishikawa',
        'FUKUI_STR':     'Fukui',
        'YAMANASHI_STR': 'Yamanashi',
        'NAGANO_STR':    'Nagano',
        'GIFU_STR':      'Gifu',
        'SHIZUOKA_STR':  'Shizuoka',
        'AICHI_STR':     'Aichi',
        'MIE_STR':       'Mie',
        'SHIGA_STR':     'Shiga',
        'KYOTO_STR':     'Kyoto',
        'OSAKA_STR':     'Osaka',
        'HYOGO_STR':     'Hyogo',
        'NARA_STR':      'Nara',
        'WAKAYAMA_STR':  'Wakayama',
        'TOTTORI_STR':   'Tottori',
        'SHIMANE_STR':   'Shimane',
        'OKAYAMA_STR':   'Okayama',
        'HIROSHIMA_STR': 'Hiroshima',
        'YAMAGUCHI_STR': 'Yamaguchi',
        'TOKUSHIMA_STR': 'Tokushima',
        'KAGAWA_STR':    'Kagawa',
        'EHIME_STR':     'Ehime',
        'KOUCHI_STR':    'Kouchi',
        'FUKUOKA_STR':   'Fukuoka',
        'SAGA_STR':      'Saga',
        'NAGASAKI_STR':  'Nagasaki',
        'KUMAMOTO_STR':  'Kumamoto',
        'OOITA_STR':     'Ooita',
        'MIYAZAKI_STR':  'Miyazaki',
        'KAGOSHIMA_STR': 'Kagoshima',
        'OKINAWA_STR':   'Okinawa',


    'ORDER_NUMBER_STR':          'Numéro d\'ordre',
    'CUSTOMER_INFO_STR':         'Information sur le client',
    'FULL_NAME_STR':             'Nom et Prénom',
    'PHONETIC_STR':              'Phonétique',
    'DATE_OF_BIRTH_STR':         'Date de naissance',
    'PHONE_NUMBER_STR':          'Numéro de téléphone',
    'DELIVERY_INFO_STR':         'Information de livraison',
    'POST_CODE_STR':             'code postal',
    'PREFECTURE_STR':            'préfecture',
    'CITY_STR':                  'Ville',
    'ADDRESS_STR':               'Address',
    'DELIVERY_COMPANY_STR':      'Société de livraison',
    'DELIVERY_DATE_STR':         'Date de livraison',
    'DELIVERY_TIME_STR':         'Délai de livraison',
    'REFRIGERATED_DELIVERY_STR': 'Livraison réfrigéré',
    'DELIVERY_COMMENT_STR':      'commentaire',
    'NOT_SPECIFIED_STR':         'Non spécifié',
    'ORDER_STATUS_STR':          'État de la commande',
    'PAID_STR':                  'Payé',
    'NOT_PAID_STR':              'Pas Payé',
    'NOT_CONFIRMED_STR':         'Pas Confirmé',
    'SHIPPED_STR':               'Expédié',
    'CONFIRM_ORDER_STR':         'Confirmer la commande.',
    'CONFIRM_PAYMENT_STR':       'Paiement confirmé.',
    'CONFIRM_ISSUE_STR':         'Confirmé rapporter.',
    'CONFIRM_DELIVERY_STR':      'Confirmé la livraison.',
    'FINALIZE_ORDER_STR':        'Finaliser l\'ordre',
    'CANCEL_ORDER_STR':          'Annuler la commande',
    'SHIPPING_AND_HANDLING_STR': 'Frais de port et de mise à disposition (TTC)',
    'TOTAL_PRICE_STR':           'Prix ​​total',	

    'PAYMENT_METHOD_STR':        'Mode de paiement',
    'CREDIT_CARD_STR':           'Carte de crédit',
    'BANK_TRANSFER_STR':         'Virement bancaire',
    'CASH_ON_DELIVERY':          'Paiement à la livraison',

    'NEED_REFRIGERATED_DELIVERY_MSG': 'Je veux une livraison réfrigéré.',
    'ADDITIONAL_200YEN_PER_CASE_MSG': 'Supplémentaire de 200 yen est facturé par cas.',
    'UNDERAGE_NOT_FOR_SALE_MSG':      'Nous n\'allons pas vendre des boissons alcooliques à des mineurs.',
    'ADD_TO_CART_STR':                'Ajouter au panier',
    'PROCEED_TO_CHECKOUT_STR':        'Passer la commande',

    'PURCHASED_WINES_STR':            'Vins achetés',

    'SPARKLING_ROSE_STR':   Constants['fr']['SPARKLING_ROSE_STR'],
    'FRENCH_WHITE_STR':     Constants['fr']['FRENCH_WHITE_STR'],
    'GERMAN_WHITE_STR':     Constants['fr']['GERMAN_WHITE_STR'],
    'AUSTRIAN_WHITE_STR':   Constants['fr']['AUSTRIAN_WHITE_STR'],
    'ITALIAN_WHITE_STR':    Constants['fr']['ITALIAN_WHITE_STR'],
    'SPANISH_WHITE_STR':    Constants['fr']['SPANISH_WHITE_STR'],
    'AMERICAN_WHITE_STR':   Constants['fr']['AMERICAN_WHITE_STR'],
    'AUSTRALIAN_WHITE_STR': Constants['fr']['AUSTRALIAN_WHITE_STR'],
    'NEWZEALAND_WHITE_STR': Constants['fr']['NEWZEALAND_WHITE_STR'],
    'FRENCH_RED_STR':       Constants['fr']['FRENCH_RED_STR'],
    'AUSTRIAN_RED_STR':     Constants['fr']['AUSTRIAN_RED_STR'],
    'GERMAN_RED_STR':       Constants['fr']['GERMAN_RED_STR'],
    'ITALIAN_RED_STR':      Constants['fr']['ITALIAN_RED_STR'],
    'SPANISH_RED_STR':      Constants['fr']['SPANISH_RED_STR'],
    'AMERICAN_RED_STR':     Constants['fr']['AMERICAN_RED_STR'],
    'AUSTRALIAN_RED_STR':   Constants['fr']['AUSTRALIAN_RED_STR'],
    'NEWZEALAND_RED_STR':   Constants['fr']['NEWZEALAND_RED_STR'],

    'HOME_TOWN_LABEL':      'ville natale /',
    'CAREER_HISTORY_LABEL': 'histoire de carrière /',
    'FAVORITE_LABEL':       'favori /',

    getString: function(stringId)
    {
        return Strings[stringId];
    }
};
