var Strings =
{
    'REMAINING_BOTTLES_FORMAT': '残り{0}本',

    'SELECT_SITE_MSG':          'ウェブサイトを選択してください。',
    'UPLOAD_SUCCESS_MSG':       'ファイルのアップロードが終了しました。',
    'TAX_INCLUDED_MSG':         '記載されております金額は、全て税込み価格です。',
    'EMPTY_FLD_MSG':            'このフィールドに入力してください。',
    'INVALID_NUMBER_MSG':       '正しい数字を入力してください。',
    'OLD_IE_MSG':               '本サイトは、古いバージョンのインターネットエクスプローラー上では正しく機能しません。　お手数ですが、下記のリンクからインターネットエクスプローラーの更新をして下さい。',
    'UNDER_CONSTRUCTION_MSG':   '申し訳ございません。只今準備中です。',
    'SUBSCRIBE_TO_ANYWAY_MAIL_MAGAZINE_MSG': '当店では定期的に、ワインに関するメールマガジンを配信しています。メールマガジンでしか入手できない情報もございますので、是非ご購読ください。',
    'INVALID_BARCODE_FOR_WINE_MSG': '入力されたバーコードのアイテムは、ワインではありません。もう一度バーコードを入力しなおして下さい。',
    'ADDED_TO_CART_MSG':            '買い物かごに、{0}本追加されました。',
    'ADDED_TO_HAPPY_BOX_MSG':       '福箱に、{0}本追加されました。',
    'NO_SALE_FOR_MINORS_MSG':       '未成年の方には酒類の販売を行いません。',

    'PREVIOUS_STR':  '前へ',
    'NEXT_STR':      '次へ',
    'SUBSCRIBE_STR': '購読する',

    'FIND_BY_WINE_TYPE':     '色で選ぶ。',
    'FIND_BY_PRODUCER_NAME': '生産者で選ぶ。',
    'FIND_BY_VINTAGE':       '年代で選ぶ。',
    'FIND_BY_PRICE':         '値段で選ぶ。',
    'FIND_BY_IMPORTER':      '輸入元で選ぶ。',

    'AGREE_STR':             '同意する',
    'NOT_AGREE_STR':         '同意しない',
    'HONEY_SUBMENU':         Constants['ja']['HONEY_SUBMENU'],
    'OLIVE_OIL_SUBMENU':     Constants['ja']['OLIVE_OIL_SUBMENU'],
    'MASTARD_SUBMENU':       Constants['ja']['MASTARD_SUBMENU'],
    'SALT_SUBMENU':          Constants['ja']['SALT_SUBMENU'],
    'DRY_FRUIT_SUBMENU':     Constants['ja']['DRY_FRUIT_SUBMENU'],

    'CORPORATE_PROFILE_STR':      Constants['ja']['CORPORATE_PROFILE_STR'],
    'PRIVACY_STR':                Constants['ja']['PRIVACY_STR'],
    'COMMERCIAL_TRANSACTION_STR': Constants['ja']['COMMERCIAL_TRANSACTION_STR'],
    'PAYMENT_METHOD_STR':         Constants['ja']['PAYMENT_METHOD_STR'],

    'SHOW_WINES_STR':        'ワインを表示',
    'UPDATE_IE_STR':         'IEの更新',
    'MITSUGETSU_STR':        '蜜月',
    'OFURO_STR':             'おふろ',
    'ANYWAY_STR':            'エニウェイ',
    'ADMIN_PAGE_STR':        '管理者用ページ',
    'PRINT_WINELIST_STR':    'ワインリストを印刷',
    'MANAGE_DB_STR':         'データーベースの管理',
    'MANAGE_ORDER_STR':      '注文の管理',
    'MODIFY_DAILY_MENU_STR': '日替わりメニューの編集',
    'UPLOAD_IMG_STR':        '画像のアップロード',
    'DB_MANAGER_PAGE_STR':   'データーベース・マネージャー',
    'SAKE_STR':              '日本酒',
    'SHOCHU_STR':            '焼酎',
    'BRANDY_STR':            'ブランデー',
    'OTHER_DRINKS_STR':      Constants['ja']['OTHER_DRINKS_STR'],
    'WINE_LIST_STR':         Constants['ja']['WINE_LIST_STR'],

    'KATAKANA_STR':           Constants['ja']['KATAKANA_STR'],
    'ALPHABET_STR':           Constants['ja']['ALPHABET_STR'],

    'SIGN_IN_STR':             'ログイン',
    'SIGN_OUT_STR':            'ログアウト',
    'ESTIMATED_SHIPPING_DATE': '商品発送予定日:&nbsp;<strong>{0}年{1}月{2}日</strong>',
    'NINETEEN_THIRTIES_STR':  '1930年代',
    'NINETEEN_FORTIES_STR':   '1940年代',
    'NINETEEN_FIFTIES_STR':   '1950年代',
    'NINETEEN_SIXTIES_STR':   '1960年代',
    'NINETEEN_SEVENTIES_STR': '1970年代',
    'NINETEEN_EIGHTIES_STR':  '1980年代',
    'NINETEEN_NITIES_STR':    '1990年代',
    'DOUBLE_O_STR':           '2000年代',

    'THOUSAND_YEN_RANGE_STR':       Constants['ja']['THOUSAND_YEN_RANGE_STR'],
    'TWO_THOUSAND_YEN_RANGE_STR':   Constants['ja']['TWO_THOUSAND_YEN_RANGE_STR'],
    'THREE_THOUSAND_YEN_RANGE_STR': Constants['ja']['THREE_THOUSAND_YEN_RANGE_STR'],
    'FOUR_THOUSAND_YEN_RANGE_STR':  Constants['ja']['FOUR_THOUSAND_YEN_RANGE_STR'],
    'FIVE_THOUSAND_YEN_RANGE_STR':  Constants['ja']['FIVE_THOUSAND_YEN_RANGE_STR'],
    'MORE_THAN_TEN_THOUSAND_STR':   Constants['ja']['MORE_THAN_TEN_THOUSAND_STR'],

    'GUARANTEED_QUALITY_STR':     Constants['ja']['GUARANTEED_QUALITY_STR'], 
    'SHIPPING_FEE_STR':           Constants['ja']['SHIPPING_FEE_STR'], 
    'BUSINESS_SALE_STR':          '業務販売',
    'USER_GUIDE_STR':             'ご利用ガイド',
    'HAPPY_BOX_GUIDE_STR':        '福箱注文方法',
    'WHATS_NEW_STR':              Constants['ja']['WHATS_NEW_STR'],
    'RECOMMENDED_WINE_STR':       'お勧めワイン',
    'VINTAGE_INFO_STR':           'ヴィンテージ',
    'MONTHLY_WINE_STR':           '今月のワイン',
    'WINE_SEARCH_STR':            '詳細検索',
    'FAQ_STR':                    'よくあるご質問',
    'WINE_SET_STR':               '送料無料セット',
    'PRODUCER_INFO_STR':          '生産者情報',
    'RANKING_STR':                'ランキング',
    'RECOMMENDED_LABEL_STR':      'ジャケ買いワイン',
    'SALE_STR':                   'セール',
    'NEW_ARRIVAL':                '新着',
    'WINE_DETAIL_STR':            'ワインの詳細',
    'IMPORTER_STR':               '輸入元',
    'CART_STR':                   '買い物カゴ',
    'COMPANY_INFO_STR':           '会社概要',
    'COMMERCIAL_TRANSACTION_STR': Constants['ja']['COMMERCIAL_TRANSACTION_STR'],
    'CONTACT_STR':                Constants['ja']['CONTACT_STR'],
    'WINE_STR':                   'ワイン',
    'OLD_WINE_STR':               '熟成ワイン',
    'FOOD_STR':                   'Food',
    'REGISTER_STR':               'ネット会員登録',
    'OTHER_INFO_STR':             'その他の情報',
    'SEARCH_STR':                 '検索する',
    'SORT_ORDER_STR':             '並び順', 
    'NUMBER_OF_MACHED_WINES':     '該当ワイン',
    'VIEW_DETAIL_STR':            '詳細を見る',

    'GLASS_WINE_STR':   Constants['ja']['GLASS_WINE_STR'],
    'BOTTLE_WINE_STR':  Constants['ja']['BOTTLE_WINE_STR'],
    'DISH_STR':         '料理',
    'GROCERY_STR':      'グロッサリー',
    'WINE_GOODS_STR':   'ワイングッズ',
    'DRINK_STR':        'Drink',
    'EVENT_STR':        'イベント',
    'PHOTO_STR':        '写真',
    'MAP_STR':          'アクセスマップ',
    'HOME_STR':         'ホーム',
    'SITE_TOP_STR':     'トップページ',
    'LANGUAGE_STR':     'Language',

    'WINE_GLASS_STR':        Constants['ja']['WINE_GLASS_STR'],
    'WINE_BASKET_STR':       Constants['ja']['WINE_BASKET_STR'],
    'CHAMPAGNE_STOPPER_STR': Constants['ja']['CHAMPAGNE_STOPPER_STR'],
    'LABEL_COLLECTOR_STR':   Constants['ja']['LABEL_COLLECTOR_STR'],

    'TYPE_STR':       '種類',
    'WINE_TYPE_STR':       'ワインの種類',
    'DISH_TYPE_STR':       '料理の種類',
    'GROCERY_TYPE_STR':    'グロッサリーの種類',
    'WINE_GOODS_TYPE_STR': 'ワイングッズの種類',
    'BRANDY_TYPE_STR':     'ブランデーの種類',
    'SAKE_TYPE_STR':    '日本酒の種類',
    'SHOCHU_TYPE_STR':  '焼酎の種類',
    'DRINK_TYPE_STR':   'ドリンクの種類',
    'EVENT_YEAR_STR':   'イベントの年',
    'PHOTO_TYPE_STR':   '写真の種類',

    'COLD_APPETIZER_STR': Constants['ja']['COLD_APPETIZER_STR'],
    'HOT_APPETIZER_STR':  Constants['ja']['HOT_APPETIZER_STR'],
    'FISH_DISH_STR':      Constants['ja']['FISH_DISH_STR'],
    'MEAT_DISH_STR':      Constants['ja']['MEAT_DISH_STR'],
    'GIBIER_STR':         Constants['ja']['GIBIER_STR'],
    'DRY_FRUIT_STR':      Constants['ja']['DRY_FRUIT_STR'],
    'MITSU_COURSE_STR':   '蜜のコースメニュー',
    'GETSU_COURSE_STR':   '月のコースメニュー',

    'AWAMORI_STR':        Constants['ja']['AWAMORI_STR'],
    'KOKUTOU_JOUCHU_STR': Constants['ja']['KOKUTOU_JOUCHU_STR'],
    'KOME_JOUCHU_STR':    Constants['ja']['KOME_JOUCHU_STR'],
    'MUGI_JOUCHU_STR':    Constants['ja']['MUGI_JOUCHU_STR'],
    'IMO_JOUCHU_STR':     Constants['ja']['IMO_JOUCHU_STR'],
    'KURI_JOUCHU_STR':    Constants['ja']['KURI_JOUCHU_STR'],

    'SHOCHU_STR': Constants['ja']['SHOCHU_STR'],
    'SAKE_STR':   Constants['ja']['SAKE_STR'],

    'MITSUGETSU_STAFF_STR':    '蜜月のスタッフ',
    'MITSUGETSU_EVENT_STR':    '蜜月イベント',
    'OFURO_STAFF_STR':         'おふろスタッフ',
    'OFURO_EVENT_STR':         'おふろイベント',

    'SHOP_PHOTO_STR':          '店内の写真',
    'TASTING_EVENT_PHOTO_STR': '試飲会の写真',
    'DISH_PHOTO_STR':          '料理の写真',
    'MAGAZINE_PHOTO_STR':      '雑誌の写真',

    'DAILY_MENU_STR':        Constants['ja']['DAILY_MENU_STR'],
    'NORMAL_MENU_STR':       Constants['ja']['NORMAL_MENU_STR'],
    'SMALL_DISH_STR':        Constants['ja']['SMALL_DISH_STR'],
    'A_LA_CARTE':            Constants['ja']['A_LA_CARTE'],
    'COURSE_STR':            Constants['ja']['COURSE_STR'],
    'APPETIZER_STR':         '前菜',
    'MAIN_DISH_STR':         '主菜',
    'PASTA_STR':             Constants['ja']['PASTA_STR'],
    'GOHAN_STR':             Constants['ja']['GOHAN_STR'],
    'CHEESE_STR':            Constants['ja']['CHEESE_STR'],
    'DESSERT_STR':           Constants['ja']['DESSERT_STR'],
    'TEA_STR':               'お茶',
    'SPARKLING_WINE_STR':    Constants['ja']['SPARKLING_WINE_STR'],
    'CHAMPAGNE_STR':         Constants['ja']['CHAMPAGNE_STR'],
    'ROSE_WINE_STR':         'ロゼワイン',
    'WHITE_WINE_STR':        '白ワイン',
    'RED_WINE_STR':          '赤ワイン',
    'ENGLISH_STR':           '英語',
    'FRENCH_STR':            'フランス語',
    'JAPANESE_STR':          '日本語',

    'NEW_ITEM_STR':        '新規のアイテム',
    'INSERT_BELOW_STR':    'アイテムを後ろに挿入',
    'EDIT_STR':            '編集',
    'DELETE_STR':          '削除',
    'EXPORT_TO_PNG':       'PNGに書き出し',
    'SAVE_STR':            '保存',
    'CANCEL_STR':          'キャンセル',
    'VINTAGE_STR':         '生産年',
    'CAPACITY_STR':        '容量',
    'MONO_YEAR_STR':       '単一年',
    'PRODUCER_STR':        '生産者',
    'LOC_PRODUCER_STR':    '生産者（日本語）',
    'FIRST_NAME_STR':      '名',
    'LAST_NAME_STR':       '姓',
    'NAME_STR':            '名前',
    'LOC_NAME_STR':        '名前（日本語）',
    'ITEM_NAME_STR':       '銘柄',
    'BARCODE_STR':         'バーコード',
    'PRICE_STR':           '価格',
    'RETAIL_PRICE_STR':    '通常価格',
    'MEMBER_PRICE_STR':    '会員価格',
    'TAX_EXCLUDED_STR':    '税抜',

    'GLASS_PRICE_STR':     '値段（１０８ｍｌ）',
    'TOKKURI_PRICE_STR':   '値段（１８０ｍｌ）',

    'INGREDIENT_STR':      '原料',
    'BOTTLING_METHOD_STR': '瓶詰め方法',
    'ROMAJI_NAME_STR':     '名前（ローマ字）',
    'HIRAGANA_NAME_STR':   '名前（ひらがな）',

    'EVENT_DATE_STR':      'イベントの日',
    'EVENT_DESCRIPTION':   'イベント内容',

    'ALCOHOL_STR':            'アルコール度数',
    'VOLUME_STR':             '容量',
    'COMMENT_STR':            'コメント',
    'ROSE_STR':               'ロゼ',
    'COUNTRY_STR':            '生産国',
    'AOC_STR':                '産地',
    'LOC_AOC_STR':            '産地(日本語)',
    'REGION_STR':             '生産地',
    'CEPAGE_STR':             'ぶどう品種',
    'MONO_CEPAGE_STR':        '単一品種',
    'CULTIVATION_METHOD_STR': '栽培方法',
    'WINE_SCORE_STR':         '評価',
    'TEL_STR':                '電話番号',
    'EMAIL_STR':              'メールアドレス',
    'OPENING_HOURS_STR':      'Open',
    'CLOSED_ON_STR':          'Close',

    'URL_STR':           'Url',
    'MONTHLY_STR':       '今月のワイン',
    'QUANTITY_STR':      '数量',
    'NEW_WINE_STR':      Constants['ja']['WINE_ARRIVAL_SUBMENU'],

    'TASTING_INFO_STR':  '試飲情報',

    'NOT_SPECIFY_STR':   '指定しない',
    'FILENAME_STR': 'ファイル名',

    'SUNDAY_STR':    '日',
    'MONDAY_STR':    '月',
    'TUESDAY_STR':   '火',
    'WEDNESDAY_STR': '水',
    'THURSDAY_STR':  '木',
    'FRIDAY_STR':    '金',
    'SATURDAY_STR':  '土',

    'FRANCE_STR':       Constants['fr']['FRANCE_STR'],
    'AUSTRALIA_STR':    Constants['fr']['AUSTRALIA_STR'],
    'GERMANY_STR':      Constants['fr']['GERMANY_STR'],
    'NEW_ZEALAND_STR':  Constants['fr']['NEW_ZEALAND_STR'],
    'ITALY_STR':        Constants['fr']['ITALY_STR'],
    'AMERICA_STR':      Constants['fr']['AMERICA_STR'],
    'SPAIN_STR':        Constants['fr']['SPAIN_STR'],
    'JAPAN_STR':        Constants['fr']['JAPAN_STR'],
    'AUSTRIA_STR':      Constants['fr']['AUSTRIA_STR'],
    'SOUTH_AFRICA_STR': Constants['fr']['SOUTH_AFRICA_STR'],
    'ENGLAND_STR':      Constants['fr']['ENGLAND_STR'],
    'CROATIA_STR':      Constants['fr']['CROATIA_STR'],
    'PORTUGAL_STR':     Constants['fr']['PORTUGAL_STR'],
    'CANADA_STR':       Constants['fr']['CANADA_STR'],
    'UKRAINE_STR':      Constants['fr']['UKRAINE_STR'],
    'ARGENTINA_STR':    Constants['fr']['ARGENTINA_STR'],
    'SWITZERLAND_STR':  Constants['fr']['SWITZERLAND_STR'],
    'BULGARIA_STR':     Constants['fr']['BULGARIA_STR'],
    'HANGARY_STR':      Constants['fr']['HANGARY_STR'],
    'LEBANON_STR':      Constants['fr']['LEBANON_STR'],
    'CHILE_STR':        Constants['fr']['CHILE_STR'],

    'CIRCLE_CHAR':    '★',
    'WORD_SEPARATOR': ' ・ ',

    'YEAR_SYMBOL':  '年',
    'MONTH_SYMBOL': '月',
    'DATE_SYMBOL':  '日',

    'SPARKLING_WINE_STR':  Constants['ja']['SPARKLING_WINE_STR'],
    'WHITE_WINE_STR':      Constants['ja']['WHITE_WINE_STR'],
    'RED_WINE_STR':        Constants['ja']['RED_WINE_STR'],
    'ROSE_WINE_STR':       Constants['ja']['ROSE_WINE_STR'],

    'CHAMPAGNE_STR':       Constants['ja']['CHAMPAGNE_STR'],
    'CHAMPAGNE_ROSE_STR':  Constants['ja']['CHAMPAGNE_ROSE_STR'],
    'CREMANT_STR':         Constants['ja']['CREMANT_STR'],
    'PETILLANT_STR':       Constants['ja']['PETILLANT_STR'],
    'OTHER_SPARKLING_STR': Constants['ja']['OTHER_SPARKLING_STR'],
    'LORRAINE_STR':        Constants['ja']['LORRAINE_STR'],
    'ALSACE_STR':          Constants['ja']['ALSACE_STR'],
    'LOIRE_STR':           Constants['ja']['LOIRE_STR'],
    'BORDEAUX_STR':        Constants['ja']['BORDEAUX_STR'],
    'SUDWEST_STR':         Constants['ja']['SUDWEST_STR'],
    'BOURGOGNE_STR':       Constants['ja']['BOURGOGNE_STR'],
    'JURA_STR':            Constants['ja']['JURA_STR'],
    'SAVOIE_FRANCHE_STR':  Constants['ja']['SAVOIE_FRANCHE_STR'],
    'RHONE_STR':           Constants['ja']['RHONE_STR'],
    'LANG_ROUS_STR':       Constants['ja']['LANG_ROUS_STR'],
    'PROVENCE_STR':        Constants['ja']['PROVENCE_STR'],
    'CORSE_STR':           Constants['ja']['CORSE_STR'],
    'JURA_FRANCHE_STR':    Constants['ja']['JURA_FRANCHE_STR'],
    'LANGUEDOC_STR':       Constants['ja']['LANGUEDOC_STR'],
    'ROUSSILLON_STR':      Constants['ja']['ROUSSILLON_STR'],
    'OTHER_LANG_ROUS_STR': Constants['ja']['OTHER_LANG_ROUS_STR'],
    'FRANCE_MAIN_STR':     Constants['ja']['FRANCE_MAIN_STR'],

    'HOKKAIDO_STR':  '北海道',
    'AOMORI_STR':    '青森県',
    'IWATE_STR':     '岩手県',
    'MIYAGI_STR':    '宮城県',
    'AKITA_STR':     '秋田県',
    'YAMAGATA_STR':  '山形県',
    'FUKUSHIMA_STR': '福島県',
    'IBARAKI_STR':   '茨城県',
    'TOCHIGI_STR':   '栃木県',
    'GUNMA_STR':     '群馬県',
    'SAITAMA_STR':   '埼玉県',
    'CHIBA_STR':     '千葉県',
    'TOKYO_STR':     '東京都',
    'KANAGAWA_STR':  '神奈川県',
    'NIIGATA_STR':   '新潟県',
    'TOYAMA_STR':    '富山県',
    'ISHIKAWA_STR':  '石川県',
    'FUKUI_STR':     '福井県',
    'YAMANASHI_STR': '山梨県',
    'NAGANO_STR':    '長野県',
    'GIFU_STR':      '岐阜県',
    'SHIZUOKA_STR':  '静岡県',
    'AICHI_STR':     '愛知県',
    'MIE_STR':       '三重県',
    'SHIGA_STR':     '滋賀県',
    'KYOTO_STR':     '京都府',
    'OSAKA_STR':     '大阪府',
    'HYOGO_STR':     '兵庫県',
    'NARA_STR':      '奈良県',
    'WAKAYAMA_STR':  '和歌山県',
    'TOTTORI_STR':   '鳥取県',
    'SHIMANE_STR':   '島根県',
    'OKAYAMA_STR':   '岡山県',
    'HIROSHIMA_STR': '広島県',
    'YAMAGUCHI_STR': '山口県',
    'TOKUSHIMA_STR': '徳島県',
    'KAGAWA_STR':    '香川県',
    'EHIME_STR':     '愛媛県',
    'KOUCHI_STR':    '高知県',
    'FUKUOKA_STR':   '福岡県',
    'SAGA_STR':      '佐賀県',
    'NAGASAKI_STR':  '長崎県',
    'KUMAMOTO_STR':  '熊本県',
    'OOITA_STR':     '大分県',
    'MIYAZAKI_STR':  '宮崎県',
    'KAGOSHIMA_STR': '鹿児島県',
    'OKINAWA_STR':   '沖縄県',

    'ORDER_NUMBER_STR':          '注文番号',
    'CUSTOMER_INFO_STR':         'お客様情報',
    'FULL_NAME_STR':             '氏名',
    'PHONETIC_STR':              'フリガナ',
    'DATE_OF_BIRTH_STR':         '生年月日',
    'PHONE_NUMBER_STR':          '電話番号',
    'DELIVERY_INFO_STR':         '配送について',
    'POST_CODE_STR':             '郵便番号',
    'PREFECTURE_STR':            '県',
    'CITY_STR':                  '市区町村',
    'ADDRESS_STR':               '住所',
    'DELIVER_TO_STR':            '配送先',
    'DELIVERY_COMPANY_STR':      '配送業者',
    'DELIVERY_DATE_STR':         '配送希望日',
    'DELIVERY_TIME_STR':         '配送希望時間',
    'REFRIGERATED_DELIVERY_STR': 'クール便',
    'DELIVERY_COMMENT_STR':      'コメント',
    'NOT_SPECIFIED_STR':         '指定なし',
    'ORDER_STATUS_STR':          'オーダーのステータス',
    'PAID_STR':                  '支払い済み',
    'NOT_PAID_STR':              '未払い',
    'NOT_CONFIRMED_STR':         '未確定',
    'SHIPPED_STR':               '発送済み',
    'CONFIRM_ORDER_STR':         '注文を確定する。',
    'CONFIRM_PAYMENT_STR':       '支払い済みにする。',
    'CONFIRM_ISSUE_STR':         '出庫済みにする。',
    'CONFIRM_DELIVERY_STR':      '発送済みにする。',
    'CANCEL_ORDER_STR':          '取り消す',
    'FINALIZE_ORDER_STR':        '完了する',
    'SHIPPING_AND_HANDLING_STR': '配送料＆手数料（税込み）',
    'TOTAL_PRICE_STR':           '合計額',

    'PAYMENT_METHOD_STR':        '支払い方法',
    'CREDIT_CARD_STR':           'クレジットカード',
    'BANK_TRANSFER_STR':         '銀行振り込み',
    'CASH_ON_DELIVERY':          '代引き',

    'NEED_REFRIGERATED_DELIVERY_MSG': 'クール便を希望する。',
    'ADDITIONAL_200YEN_PER_CASE_MSG': '1ケースにつき200円の送料が追加になります。',
    'UNDERAGE_NOT_FOR_SALE_MSG':      '未成年者の方には酒類の販売を行いません。',
    'ADD_TO_CART_STR':                '買い物かごに入れる',
    'PROCEED_TO_CHECKOUT_STR':        'レジに進む',

    'PURCHASED_WINES_STR':            '購入ワイン',

    'SPARKLING_ROSE_STR':   Constants['ja']['SPARKLING_ROSE_STR'],
    'FRENCH_WHITE_STR':     Constants['ja']['FRENCH_WHITE_STR'],
    'GERMAN_WHITE_STR':     Constants['ja']['GERMAN_WHITE_STR'],
    'AUSTRIAN_WHITE_STR':   Constants['ja']['AUSTRIAN_WHITE_STR'],
    'ITALIAN_WHITE_STR':    Constants['ja']['ITALIAN_WHITE_STR'],
    'SPANISH_WHITE_STR':    Constants['ja']['SPANISH_WHITE_STR'],
    'AMERICAN_WHITE_STR':   Constants['ja']['AMERICAN_WHITE_STR'],
    'AUSTRALIAN_WHITE_STR': Constants['ja']['AUSTRALIAN_WHITE_STR'],
    'NEWZEALAND_WHITE_STR': Constants['ja']['NEWZEALAND_WHITE_STR'],
    'FRENCH_RED_STR':       Constants['ja']['FRENCH_RED_STR'],
    'AUSTRIAN_RED_STR':     Constants['ja']['AUSTRIAN_RED_STR'],
    'GERMAN_RED_STR':       Constants['ja']['GERMAN_RED_STR'],
    'ITALIAN_RED_STR':      Constants['ja']['ITALIAN_RED_STR'],
    'SPANISH_RED_STR':      Constants['ja']['SPANISH_RED_STR'],
    'AMERICAN_RED_STR':     Constants['ja']['AMERICAN_RED_STR'],
    'AUSTRALIAN_RED_STR':   Constants['ja']['AUSTRALIAN_RED_STR'],
    'NEWZEALAND_RED_STR':   Constants['ja']['NEWZEALAND_RED_STR'],

    getString: function(stringId)
    {
        return Strings[stringId];
    }
};
