var Strings =
{
    'REMAINING_BOTTLES_FORMAT': '{0} bottles left',

    'SELECT_SITE_MSG':    'Select the Web site.',
    'UPLOAD_SUCCESS_MSG': 'The file was uploaded successfully.',
    'TAX_INCLUDED_MSG':   'The price of the list includes tax.',
    'EMPTY_FLD_MSG':      'Please fill out this field.',
    'INVALID_NUMBER_MSG': 'Please input a valid number.',
    'OLD_IE_MSG':         'You are using old version of Internet Explorer. Please click one of the below links and update your Internet Explorer.',
    'UNDER_CONSTRUCTION_MSG':   'The contents is under construction.  Sorry for the inconvenience.',
    'SUBSCRIBE_TO_ANYWAY_MAIL_MAGAZINE_MSG': 'Subscribe to the mail magazine of "Conceptual Wine Boutique Anyway-Grapes".',
    'INVALID_BARCODE_FOR_WINE_MSG': 'The item with the specified barcode is not a wine.  Please re-type a barcode.',
    'ADDED_TO_CART_MSG':      '{0} bottles were added to the cart.',
    'ADDED_TO_HAPPY_BOX_MSG': '{0} bottles were added to the Happy Box.',
    'NO_SALE_FOR_MINORS_MSG': 'We do not sell alcohol to minors.',

    'FIND_BY_WINE_TYPE':     '> Find by wine type.',
    'FIND_BY_PRODUCER_NAME': '> Find by producer.',
    'FIND_BY_VINTAGE':       '> Find by vintage.',
    'FIND_BY_PRICE':         '> Find by price.',
    'FIND_BY_IMPORTER':      '> Find by importer.',

    'AGREE_STR':             'Agree',
    'NOT_AGREE_STR':         'Do not agree',

    'CORPORATE_PROFILE_STR':      Constants['en']['CORPORATE_PROFILE_STR'],
    'PRIVACY_STR':                Constants['en']['PRIVACY_STR'],
    'COMMERCIAL_TRANSACTION_STR': Constants['en']['COMMERCIAL_TRANSACTION_STR'],
    'PAYMENT_METHOD_STR':         Constants['en']['PAYMENT_METHOD_STR'],

    'HONEY_SUBMENU':         Constants['en']['HONEY_SUBMENU'],
    'OLIVE_OIL_SUBMENU':     Constants['en']['OLIVE_OIL_SUBMENU'],
    'MASTARD_SUBMENU':       Constants['en']['MASTARD_SUBMENU'],
    'SALT_SUBMENU':          Constants['en']['SALT_SUBMENU'],
    'DRY_FRUIT_SUBMENU':     Constants['en']['DRY_FRUIT_SUBMENU'],

    'PREVIOUS_STR':  'Previous',
    'NEXT_STR':      'Next',
    'SUBSCRIBE_STR': 'Subscribe',

    'SHOW_WINES_STR':        'Show Wines',
    'UPDATE_IE_STR':         'Update IE',
    'MITSUGETSU_STR':        'Mitsu-Getsu',
    'OFURO_STR':             'Ofuro',
    'ANYWAY_STR':            'Anyway',
    'ADMIN_PAGE_STR':        'Administration Page',
    'PRINT_WINELIST_STR':    'Print out wine list',
    'MANAGE_DB_STR':         'Manage databases',
    'MANAGE_ORDER_STR':      'Manage orders',
    'MODIFY_DAILY_MENU_STR': 'Modify daily menu',
    'UPLOAD_IMG_STR':        'Upload image',
    'DB_MANAGER_PAGE_STR':   'Database Manager',
    'SAKE_STR':              Constants['en']['SAKE_STR'],
    'SHOCHU_STR':            Constants['en']['SHOCHU_STR'],
    'BRANDY_STR':            'Brandy',
    'OTHER_DRINKS_STR':      Constants['en']['OTHER_DRINKS_STR'],
    'WINE_LIST_STR':         Constants['en']['WINE_LIST_STR'],

    'KATAKANA_STR':           Constants['en']['KATAKANA_STR'],
    'ALPHABET_STR':           Constants['en']['ALPHABET_STR'],
    'SIGN_IN_STR':            'Sign In',
    'SIGN_OUT_STR':           'Sign Out',

    'ESTIMATED_SHIPPING_DATE': 'Estimated Shipping Date:&nbsp;<strong>{1}/{2}/{0}</strong>',
    'NINETEEN_THIRTIES_STR':  '1930s',
    'NINETEEN_FORTIES_STR':   '1940s',
    'NINETEEN_FIFTIES_STR':   '1950s',
    'NINETEEN_SIXTIES_STR':   '1960s',
    'NINETEEN_SEVENTIES_STR': '1970s',
    'NINETEEN_EIGHTIES_STR':  '1980s',
    'NINETEEN_NITIES_STR':    '1990s',
    'DOUBLE_O_STR':           '2000s',

    'THOUSAND_YEN_RANGE_STR':       Constants['en']['THOUSAND_YEN_RANGE_STR'],
    'TWO_THOUSAND_YEN_RANGE_STR':   Constants['en']['TWO_THOUSAND_YEN_RANGE_STR'],
    'THREE_THOUSAND_YEN_RANGE_STR': Constants['en']['THREE_THOUSAND_YEN_RANGE_STR'],
    'FOUR_THOUSAND_YEN_RANGE_STR':  Constants['en']['FOUR_THOUSAND_YEN_RANGE_STR'],
    'FIVE_THOUSAND_YEN_RANGE_STR':  Constants['en']['FIVE_THOUSAND_YEN_RANGE_STR'],
    'MORE_THAN_TEN_THOUSAND_STR':   Constants['en']['MORE_THAN_TEN_THOUSAND_STR'],

    'NEW_WINE_STR':      Constants['en']['WINE_ARRIVAL_SUBMENU'],
    'RECOMMENDED_WINE_STR': 'Recommended Wine',
    'VINTAGE_INFO_STR':     'Vintage Info',
    'MONTHLY_WINE_STR':     'Monthly Wines',
    'WINE_SEARCH_STR':      'Advanced Search',
    'FAQ_STR':              'FAQ',
    'WINE_SET_STR':         'Wine Set',
    'PRODUCER_INFO_STR':    'Producer Info',
    'RANKING_STR':          'Ranking',
    'RECOMMENDED_LABEL_STR': 'Recommended Label',
    'SALE_STR':         'Sale',
    'NEW_ARRIVAL':      'New Arrival',
    'WINE_DETAIL_STR':  'Wine Detail',
    'IMPORTER_STR':     Constants['en']['IMPORTER_STR'],
    'CART_STR':         'Shopping Cart',
    'COMPANY_INFO_STR': 'Company Info',
    'COMMERCIAL_TRANSACTION_STR': 'Act on Specified Commercial Transactions',
    'CONTACT_STR':      'Contact',

    'GUARANTEED_QUALITY_STR':     Constants['en']['GUARANTEED_QUALITY_STR'], 
    'SHIPPING_FEE_STR':           Constants['en']['SHIPPING_FEE_STR'], 
    'BUSINESS_SALE_STR': 'Business Sale',
    'USER_GUIDE_STR':   'User Guide',
    'HAPPY_BOX_GUIDE_STR': 'How to order Happy Box',
    'WHATS_NEW_STR':    Constants['en']['WHATS_NEW_STR'],
    'WINE_STR':         Constants['en']['WINE_STR'],
    'OLD_WINE_STR':     'Old Wine',
    'FOOD_STR':         Constants['en']['FOOD_STR'],
    'GROCERY_STR':      'Grocery',
    'WINE_GOODS_STR':   'Wine Goods',
    'REGISTER_STR':     Constants['en']['REGISTER_STR'],
    'OTHER_INFO_STR':    'Other Info',
    'SEARCH_STR':        'Search',
    'SORT_ORDER_STR':    'Sort Order',
    'NUMBER_OF_MACHED_WINES': 'Number of matched wines',
    'VIEW_DETAIL_STR':   'View Detail',

    'GLASS_WINE_STR':   Constants['en']['GLASS_WINE_STR'],
    'BOTTLE_WINE_STR':  Constants['en']['BOTTLE_GLASS_STR'],
    'DISH_STR':         'Dish',
    'DRINK_STR':        Constants['en']['DRINK_STR'],
    'EVENT_STR':        Constants['en']['EVENT_STR'],
    'PHOTO_STR':        Constants['en']['PHOTO_STR'],
    'MAP_STR':          Constants['en']['MAP_STR'],
    'HOME_STR':         'Home',
    'SITE_TOP_STR':     Constants['en']['SITE_TOP_STR'],
    'LANGUAGE_STR':     'Language',

    'WINE_GLASS_STR':        Constants['en']['WINE_GLASS_STR'],
    'WINE_BASKET_STR':       Constants['en']['WINE_BASKET_STR'],
    'CHAMPAGNE_STOPPER_STR': Constants['en']['CHAMPAGNE_STOPPER_STR'],
    'LABEL_COLLECTOR_STR':   Constants['en']['LABEL_COLLECTOR_STR'],

    'TYPE_STR':            'Type',
    'WINE_TYPE_STR':       'Type of wine',
    'DISH_TYPE_STR':       'Type of dish',
    'GROCERY_TYPE_STR':    'Type of grocery',
    'WINE_GOODS_TYPE_STR': 'Type of wine goods',
    'BRANDY_TYPE_STR':     'Type of brandy',
    'SAKE_TYPE_STR':       'Type of sake',
    'SHOCHU_TYPE_STR':     'Type of shochu',
    'DRINK_TYPE_STR':      'Type of drink',
    'EVENT_YEAR_STR':      'Year of event',
    'PHOTO_TYPE_STR':      'Type of photo',

    'COLD_APPETIZER_STR':  Constants['en']['COLD_APPETIZER_STR'],
    'HOT_APPETIZER_STR':   Constants['en']['HOT_APPETIZER_STR'],
    'FISH_DISH_STR':       Constants['en']['FISH_DISH_STR'],
    'MEAT_DISH_STR':       Constants['en']['MEAT_DISH_STR'],
    'GIBIER_STR':          Constants['en']['GIBIER_STR'],
    'DRY_FRUIT_STR':       Constants['en']['DRY_FRUIT_STR'],
    'MITSU_COURSE_STR':   'Course Menu of The MITSU',
    'GETSU_COURSE_STR':   'Course Menu of The GETSU',

    'DAILY_MENU_STR':        Constants['en']['DAILY_MENU_STR'],
    'NORMAL_MENU_STR':       Constants['en']['NORMAL_MENU_STR'],
    'APPETIZER_STR':         'Appetizer',
    'MAIN_DISH_STR':         'Main Dish',
    'SMALL_DISH_STR':        Constants['en']['SMALL_DISH_STR'],
    'A_LA_CARTE':            Constants['en']['A_LA_CARTE'],
    'PASTA_STR':             Constants['en']['PASTA_STR'],
    'GOHAN_STR':             Constants['en']['GOHAN_STR'],
    'CHEESE_STR':            Constants['en']['CHEESE_STR'],
    'DESSERT_STR':           Constants['en']['DESSERT_STR'],
    'TEA_STR':               'Tea',
    'COURSE_STR':            Constants['en']['COURSE_STR'],

    'AWAMORI_STR':        'Awamori',
    'KOKUTOU_JOUCHU_STR': 'Kokutou-Jouchu',
    'KOME_JOUCHU_STR':    'Kome-Jouchu',
    'MUGI_JOUCHU_STR':    'Mugi-Jouchu',
    'IMO_JOUCHU_STR':     'Imo-Jouchu',
    'KURI_JOUCHU_STR':    'Kuri-Jouchu',

    'MITSUGETSU_STAFF_STR': 'Mitsu-Getsu Staff',
    'MITSUGETSU_EVENT_STR': 'Mitsu-Getsu Event',
    'OFURO_STAFF_STR':      'Ofuro Staff',
    'OFURO_EVENT_STR':      'Ofuro Event',

    'SHOP_PHOTO_STR':          'Shop Photo',
    'TASTING_EVENT_PHOTO_STR': 'Tasting Event Photo',
    'DISH_PHOTO_STR':          'Dish Photo',
    'MAGAZINE_PHOTO_STR':      'Magazine Photo',

    'SHOCHU_STR': 'Shochu',
    'SAKE_STR':   'Sake',

    'SPARKLING_WINE_STR': Constants['en']['SPARKLING_WINE_STR'],
    'CHAMPAGNE_STR':      Constants['en']['CHAMPAGNE_STR'],
    'ROSE_WINE_STR':      Constants['en']['ROSE_WINE_STR'],
    'WHITE_WINE_STR':     Constants['en']['WHITE_WINE_STR'],
    'RED_WINE_STR':       Constants['en']['RED_WINE_STR'],
    'ENGLISH_STR':        'English',
    'FRENCH_STR':         'French',
    'JAPANESE_STR':       'Japanese',

    'NEW_ITEM_STR':      'New Item',
    'INSERT_BELOW_STR':  'Insert Below',
    'EDIT_STR':          'Edit',
    'DELETE_STR':        'Delete',
    'EXPORT_TO_PNG':     'Export to PNG',
    'SAVE_STR':          'Save',
    'CANCEL_STR':        'Cancel',
    'VINTAGE_STR':       'Vintage',
    'CAPACITY_STR':       'Capacity',
    'MONO_YEAR_STR':     'Mono year',
    'PRODUCER_STR':      'Producer',
    'LOC_PRODUCER_STR':  'Producer(Japanese)',
    'FIRST_NAME_STR':    'First Name',
    'LAST_NAME_STR':     'Last Name',
    'NAME_STR':          'Name',
    'LOC_NAME_STR':      'Name(Japanese)',
    'ITEM_NAME_STR':     'Item Name',
    'BARCODE_STR':       'Barcode',
    'MEMBER_PRICE_STR':  'Member Price',
    'PRICE_STR':         'Price',
    'GLASS_PRICE_STR':   'Price (108ml)',
    'TOKKURI_PRICE_STR': 'Price (180ml)',
    'INGREDIENT_STR':    'Ingredient',
    'BOTTLING_METHOD_STR': 'Bottling Method',
    'ROMAJI_NAME_STR':     'Name(English)',
    'HIRAGANA_NAME_STR':   'Name(Hiragana)',

    'EVENT_DATE_STR':      'Event Date',
    'EVENT_DESCRIPTION':   'Event Description',

    'ALCOHOL_STR':            'Alcohol',
    'VOLUME_STR':             'Volume',
    'COMMENT_STR':            'Comment',
    'COUNTRY_STR':            'Country',
    'ROSE_STR':               'Rosé',
    'AOC_STR':                'AOC',
    'LOC_AOC_STR':            'AOC(Japanese)',
    'REGION_STR':             'Region',
    'CEPAGE_STR':             'Cepage',
    'MONO_CEPAGE_STR':        'Single Varietal',
    'CULTIVATION_METHOD_STR': 'Cultivation Method',
    'WINE_SCORE_STR':         'Wine Score',
    'ADDRESS_STR':            'Address',
    'TEL_STR':                'Tel',
    'EMAIL_STR':              'Email',
    'OPENING_HOURS_STR':      'Opening Hours',
    'CLOSED_ON_STR':          'Closed on',
    'URL_STR':                'Url',
    'MONTHLY_STR':            'Monthly',
    'QUANTITY_STR':           'Quantity',

    'NOT_SPECIFY_STR':   'Do not specify.',
    'FILENAME_STR': 'File Name',
    'TASTING_INFO_STR':  Constants['en']['TASTING_INFO_STR'],

    'SUNDAY_STR':    Constants['en']['SUNDAY_STR'],
    'MONDAY_STR':    Constants['en']['MONDAY_STR'],
    'TUESDAY_STR':   Constants['en']['TUESDAY_STR'],
    'WEDNESDAY_STR': Constants['en']['WEDNESDAY_STR'],
    'THURSDAY_STR':  Constants['en']['THURSDAY_STR'],
    'FRIDAY_STR':    Constants['en']['FRIDAY_STR'],
    'SATURDAY_STR':  Constants['en']['SATURDAY_STR'],

    'FRANCE_STR':       Constants['fr']['FRANCE_STR'],
    'AUSTRALIA_STR':    Constants['fr']['AUSTRALIA_STR'],
    'GERMANY_STR':      Constants['fr']['GERMANY_STR'],
    'NEW_ZEALAND_STR':  Constants['fr']['NEW_ZEALAND_STR'],
    'ITALY_STR':        Constants['fr']['ITALY_STR'],
    'AMERICA_STR':      Constants['fr']['AMERICA_STR'],
    'SPAIN_STR':        Constants['fr']['SPAIN_STR'],
    'JAPAN_STR':        Constants['fr']['JAPAN_STR'],
    'AUSTRIA_STR':      Constants['fr']['AUSTRIA_STR'],
    'SOUTH_AFRICA_STR': Constants['fr']['SOUTH_AFRICA_STR'],
    'ENGLAND_STR':      Constants['fr']['ENGLAND_STR'],
    'CROATIA_STR':      Constants['fr']['CROATIA_STR'],
    'PORTUGAL_STR':     Constants['fr']['PORTUGAL_STR'],
    'CANADA_STR':       Constants['fr']['CANADA_STR'],
    'UKRAINE_STR':      Constants['fr']['UKRAINE_STR'],
    'ARGENTINA_STR':    Constants['fr']['ARGENTINA_STR'],
    'SWITZERLAND_STR':  Constants['fr']['SWITZERLAND_STR'],
    'BULGARIA_STR':     Constants['fr']['BULGARIA_STR'],
    'HANGARY_STR':      Constants['fr']['HANGARY_STR'],
    'LEBANON_STR':      Constants['fr']['LEBANON_STR'],
    'CHILE_STR':        Constants['fr']['CHILE_STR'],

    'RETAIL_PRICE_STR': 'Retail Price',
    'MEMBER_PRICE_STR': 'Member Price',
    'TAX_EXCLUDED_STR': 'w/o Tax',

    'CIRCLE_CHAR': '★',
    'WORD_SEPARATOR': ' ・ ',

    'YEAR_SYMBOL': '',
    'MONTH_SYMBOL': '',
    'DATE_SYMBOL': '',

    'SPARKLING_WINE_STR': 'Sparkling Wine',
    'WHITE_WINE_STR': 'White Wine',
    'RED_WINE_STR': 'Red Wine',
    'ROSE_WINE_STR': 'Rosé Wine',

    'CHAMPAGNE_STR': 'Champagne',
    'CHAMPAGNE_ROSE_STR': 'Champagne Rosé',
    'CREMANT_STR': 'Crémant',
    'PETILLANT_STR': 'Pétillant',
    'OTHER_SPARKLING_STR': 'Autres Vins Mousseux',
    'LORRAINE_STR': 'Lorraine',
    'ALSACE_STR': 'Alsace',
    'LOIRE_STR': 'Vallée de la Loire',
    'BORDEAUX_STR': 'Bordeaux',
    'SUDWEST_STR': 'Sud-Ouest',
    'BOURGOGNE_STR': 'Bourgogne',
    'JURA_STR': 'Jura',
    'SAVOIE_FRANCHE_STR': 'Savoie & Franche-Comté',
    'RHONE_STR': 'Vallée du Rhône',
    'LANG_ROUS_STR': 'Languedoc & Roussillon',
    'PROVENCE_STR': 'Provence',
    'CORSE_STR': 'Corse',
    'JURA_FRANCHE_STR': 'Jura & Franche-Comté',
    'LANGUEDOC_STR': 'Languedoc',
    'ROUSSILLON_STR': 'Roussillon',
    'OTHER_LANG_ROUS_STR': 'Autres Vignobles de Languedoc et Roussillon',
    'FRANCE_MAIN_STR': 'C\'est Principalement du Français',

    'HOKKAIDO_STR':  'Hokkaido',
    'AOMORI_STR':    'Aomori',
    'IWATE_STR':     'Iwate',
    'MIYAGI_STR':    'Miyagi',
    'AKITA_STR':     'Akita',
    'YAMAGATA_STR':  'Yamagata',
    'FUKUSHIMA_STR': 'Fukushima',
    'IBARAKI_STR':   'Ibaraki',
    'TOCHIGI_STR':   'Tochigi',
    'GUNMA_STR':     'Gunma',
    'SAITAMA_STR':   'Saitama',
    'CHIBA_STR':     'Chiba',
    'TOKYO_STR':     'Tokyo',
    'KANAGAWA_STR':  'Kanagawa',
    'NIIGATA_STR':   'Niigata',
    'TOYAMA_STR':    'Toyama',
    'ISHIKAWA_STR':  'Ishikawa',
    'FUKUI_STR':     'Fukui',
    'YAMANASHI_STR': 'Yamanashi',
    'NAGANO_STR':    'Nagano',
    'GIFU_STR':      'Gifu',
    'SHIZUOKA_STR':  'Shizuoka',
    'AICHI_STR':     'Aichi',
    'MIE_STR':       'Mie',
    'SHIGA_STR':     'Shiga',
    'KYOTO_STR':     'Kyoto',
    'OSAKA_STR':     'Osaka',
    'HYOGO_STR':     'Hyogo',
    'NARA_STR':      'Nara',
    'WAKAYAMA_STR':  'Wakayama',
    'TOTTORI_STR':   'Tottori',
    'SHIMANE_STR':   'Shimane',
    'OKAYAMA_STR':   'Okayama',
    'HIROSHIMA_STR': 'Hiroshima',
    'YAMAGUCHI_STR': 'Yamaguchi',
    'TOKUSHIMA_STR': 'Tokushima',
    'KAGAWA_STR':    'Kagawa',
    'EHIME_STR':     'Ehime',
    'KOUCHI_STR':    'Kouchi',
    'FUKUOKA_STR':   'Fukuoka',
    'SAGA_STR':      'Saga',
    'NAGASAKI_STR':  'Nagasaki',
    'KUMAMOTO_STR':  'Kumamoto',
    'OOITA_STR':     'Ooita',
    'MIYAZAKI_STR':  'Miyazaki',
    'KAGOSHIMA_STR': 'Kagoshima',
    'OKINAWA_STR':   'Okinawa',


    'ORDER_NUMBER_STR':          'Order Number',
    'CUSTOMER_INFO_STR':         'Customer Information',
    'FULL_NAME_STR':             'Full Name',
    'PHONETIC_STR':              'Phonetic',
    'DATE_OF_BIRTH_STR':         'Date of Birth',
    'PHONE_NUMBER_STR':          'Phone Number',
    'DELIVERY_INFO_STR':         'Delivery Information',
    'POST_CODE_STR':             'Post Code',
    'PREFECTURE_STR':            'Prefecture',
    'CITY_STR':                  'City',
    'ADDRESS_STR':               'Address',
    'DELIVER_TO_STR':            'Deliver to',
    'DELIVERY_COMPANY_STR':      'Delivery Company',
    'DELIVERY_DATE_STR':         'Delivery Date',
    'DELIVERY_TIME_STR':         'Delivery Time',
    'REFRIGERATED_DELIVERY_STR': 'Refrigerated Delivery',
    'DELIVERY_COMMENT_STR':      'Comment',
    'NOT_SPECIFIED_STR':         'Not specified',
    'ORDER_STATUS_STR':          'Order Status',
    'PAID_STR':                  'Payed',
    'NOT_PAID_STR':              'Not Payed',
    'NOT_CONFIRMED_STR':         'Not Confirmed',
    'SHIPPED_STR':               'Shipped',
    'CONFIRM_ORDER_STR':         'Confirm Order',
    'CONFIRM_PAYMENT_STR':       'Confirm Payment',
    'CONFIRM_ISSUE_STR':         'Confirm Issue',
    'CONFIRM_DELIVERY_STR':      'Confirm Delivery',
    'FINALIZE_ORDER_STR':        'Finalize Order',
    'CANCEL_ORDER_STR':          'Cancel Order',
    'SHIPPING_AND_HANDLING_STR': 'Shipping & Handling Fees (Tax included)',
    'TOTAL_PRICE_STR':           'Total Price',

    'PAYMENT_METHOD_STR':        'Payment method',
    'CREDIT_CARD_STR':           'Credit card',
    'BANK_TRANSFER_STR':         'Bank Transfer',
    'CASH_ON_DELIVERY':          'Cash on Delivery',

    'NEED_REFRIGERATED_DELIVERY_MSG': 'I want a refrigerated delivery.',
    'ADDITIONAL_200YEN_PER_CASE_MSG': 'Additional 200 yen is charged per case.',
    'UNDERAGE_NOT_FOR_SALE_MSG':      'We will not sell alcoholic beverages to the minors.',
    'ADD_TO_CART_STR':                'Add to Cart',
    'PROCEED_TO_CHECKOUT_STR':        'Proceed to checkout',

    'PURCHASED_WINES_STR':       'Purchased wines',

    'SPARKLING_ROSE_STR':   Constants['fr']['SPARKLING_ROSE_STR'],
    'FRENCH_WHITE_STR':     Constants['fr']['FRENCH_WHITE_STR'],
    'GERMAN_WHITE_STR':     Constants['fr']['GERMAN_WHITE_STR'],
    'AUSTRIAN_WHITE_STR':   Constants['fr']['AUSTRIAN_WHITE_STR'],
    'ITALIAN_WHITE_STR':    Constants['fr']['ITALIAN_WHITE_STR'],
    'SPANISH_WHITE_STR':    Constants['fr']['SPANISH_WHITE_STR'],
    'AMERICAN_WHITE_STR':   Constants['fr']['AMERICAN_WHITE_STR'],
    'AUSTRALIAN_WHITE_STR': Constants['fr']['AUSTRALIAN_WHITE_STR'],
    'NEWZEALAND_WHITE_STR': Constants['fr']['NEWZEALAND_WHITE_STR'],
    'FRENCH_RED_STR':       Constants['fr']['FRENCH_RED_STR'],
    'AUSTRIAN_RED_STR':     Constants['fr']['AUSTRIAN_RED_STR'],
    'GERMAN_RED_STR':       Constants['fr']['GERMAN_RED_STR'],
    'ITALIAN_RED_STR':      Constants['fr']['ITALIAN_RED_STR'],
    'SPANISH_RED_STR':      Constants['fr']['SPANISH_RED_STR'],
    'AMERICAN_RED_STR':     Constants['fr']['AMERICAN_RED_STR'],
    'AUSTRALIAN_RED_STR':   Constants['fr']['AUSTRALIAN_RED_STR'],
    'NEWZEALAND_RED_STR':   Constants['fr']['NEWZEALAND_RED_STR'],

    getString: function(stringId)
    {
        return Strings[stringId];
    }
};
