var Strings =
{
    'ADMIN_PAGE_STR':                   'Page pour gérer',
    'ANYWAY_STR':                       'Conceptual Wine Boutique Anyway Grapes',
    'HONEYMOON_STR':                    'Wine Tasting Space Honey Moon',
    'HIMAWARI_STR':                     'Himawari',
    'MITSUGETSU_STR':                   'Mitsu-Getsu',
    'OFURO_STR':                        'Izakaya Ofuro',
    'PRINT_WINELIST_STR':               'Imprimer la carte des vins',
    'CREATE_RECOMMENDATION_LIST_STR':   'Créer une liste de recommandation',
    'PRINT_PRICETAG_STR':               'Imprimer l\'étiquette',
    'PURCHASE_HISTORY_MGR_STR':         'Gérer historiques d\'achat',
    'REGISTER_PRODUCER_INFO':           'Resiter auprès du producteur',
    'SEND_ORDER_CONFIRMATION_MAIL_STR': 'Envoyer une confirmation de commande électronique.',
    'MANAGE_DB_STR':                    'Gérer base de donée',
    'SHOW_WINE_INFO_STR':               'Afficher les infos du vin',
    'MITSUGETSU_GOODS_ISSUE_STR':       'Question des marchandises à Mitsu-Getsu',
    'RESERVE_WINES_STR':                'Réserver le vin',
    'MANAGE_ONLINE_INVENTORY_STR':      'Gérer l\'inventaire en ligne',
    'MANAGE_WINELIST_STR':              'Gérer la carte des vins',
    'MANAGE_ORDER_STR':                 'Gérer les commandes',
    'MODIFY_DAILY_MENU_STR':            'Modifier menu du jour',
    'PHOTO_UPLOAD_STR':                 'Photo Upload',
    'CHECK_SOLD_OUT_WINE_STR':          'Vérifier vin soldout',
    'UPDATE_TASTING_INFO_STR':          'Mettre à jour les informations dégustation',
    'SELECT_SITE_MSG':                  'Choisir la site de Web.'
};
